config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :patients
  resources :pros
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

  get '/:page'=> 'static#show'


  root to: 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :pros
  validates :doctor_id, presence: true
  has_one :doctor
  belongs_to :user
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    @doctors = Doctor.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])
    @doctor = Doctor.find(@patient.doctor_id)
    @pros = @patient.pros
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:doctor_id, :name, :address, :dob, :comment, :email, :phone, :tech_ability, :diagnostic, :estadio, :treatment)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <span>this will be removed, handled automatically with logins</span>
  <div class="field">
    <%= form.label "Doctor's ID" %>
    <%= form.number_field :doctor_id, id: :patient_doctor_id %>
  </div>

  <div class="field">
    <%= form.label "Nombre" %>
    <%= form.text_field :name, id: :patient_name %>
  </div>

  <div class="field">
    <%= form.label "Dirección" %>
    <%= form.text_area :address, id: :patient_address %>
  </div>

  <div class="field">
    <%= form.label "Fecha de nacimiento" %>
    <%= form.text_area :dob, id: :patient_dob %>
  </div>

  <div class="field">
    <%= form.label "Comentarios" %>
    <%= form.text_area :comment, id: :patient_comment %>
  </div>

  <div class="field">
    <%= form.label "Correo electrónico" %>
    <%= form.text_area :email, id: :patient_email%>
  </div>

  <div class="field">
    <%= form.label "Teléfono" %>
    <%= form.text_area :phone, id: :patient_phone%>
  </div>

  <div class = "field">
    <%= form.label "Diagnostico"%>
    <%= form.text_area :diagnostic, id: :patient_diagnosis%>
  </div>


  <div class="field">
    <%= form.label "Habilidad Tecnológica"%>
    <select name="patient[tech_ability]">
      <option value="">Please select</option>
    <option value="1">Baja</option>
    <option value="2">Media</option>
    <option value="3">Alta</option>
  </select>
  </div>

  <div class = "doctor-fills">
    <div class = "field">
      <%=form.label "Estadío Clínico"%>
      <%= form.text_area :estadio, id: :patient_estadio%>
    </div>

    <div class = "field">
      <%= form.label "Tratamiento" %>
      <%= form.text_area :treatment, id: :patient_treatment%>
    </div>
  </div>


  <div class="actions">
    <%= form.submit "Guardar Perfil" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Mostrar', @patient %> |
<%= link_to 'Regresar', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<table>
  <thead>
    <tr>
      <th class="colorize0">Doctor</th>
      <th>Nombre</th>
      <th>Dirección</th>
      <th>Fecha de Nacimiento</th>
      <th>Comentarios</th>
      <th>Correo electrónico</th>
      <th>Teléfono</th>
      <th>Habilidad Tecnológica</th>
      <th>Diagnóstico</th>
      <th>Estadío Clínico</th>
      <th>Tratamiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td> <%doctor = @doctors.find(patient.doctor_id)%>
          <%= link_to doctor.name, doctor_path(doctor.id)  %></td>
        <td><%= link_to patient.name, patient %></td>
        <td><%= patient.address %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.comment %></td>
        <td><%= patient.email %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.tech_ability %></td>
        <td><%= patient.diagnostic %></td>
        <td><%= patient.estadio %></td>
        <td><%= patient.treatment%></td>
        <td><%= link_to 'Borrar', patient, method: :delete, data: { confirm: 'Estas seguro que deseas borrar este perfil?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Paciente', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Regresar', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%=link_to @doctor.name, doctor_path(@doctor) %>
</p>

<p>
  <strong>Nombre del Paciente:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Fecha de Nacimiento:</strong>
  <%= @patient.dob %>
</p>

<p>
  <strong>Comentarios:</strong>
  <%= @patient.comment %>
</p>

<p>
  <strong>Correo Electrónico:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Habilidad Tecnológica:</strong>
  <%= @patient.tech_ability %>
</p>

<p>
  <strong>Diagnóstico: </strong>
  <%= @patient.diagnostic %>
</p>

<p>
  <strong>Estadío Clínico: </strong>
  <%= @patient.estadio %>
</p>

<p>
  <strong>Tratamiento: </strong>
  <%= @patient.treatment %>
</p>


<div>
  <h1>Encuestas Contestadas</h1>

  <table>
    <thead>
      <tr>
        <th><span class="colorize0" title="Dolor">Q1</span></th>
        <th><span class="colorize0" title="Falta de Aliento o Tos">Q2</span></th>
        <th><span class="colorize0" title="Nausea o Vómito">Q3</span></th>
        <th><span class="colorize0" title="Fatiga o Somnolencia">Q4</span></th>
        <th><span class="colorize0" title="Angustia">Q5</span></th>
        <th><span class="colorize0" title="Diarrea">Q6</span></th>
        <th><span class="colorize0" title="Problemas de Atención, Memoria o Coordinación">Q7</span></th>
        <th><span class="colorize0" title="Falta de Apetito">Q8</span></th>
        <th><span class="colorize0" title="Constipación">Q9</span></th>
        <th><span class="colorize0" title="Resequedad u otros Malestares en la Boca">Q10</span></th>
        <th><span class="colorize0" title="Insomnio">Q11</span></th>
        <th><span class="colorize0" title="Tristeza">Q12</span></th>
        <th><span class="colorize0" title="Fiebre">Q13</span></th>
        <th><span class="colorize0" title="Actividad General">Q14</span></th>
        <th><span class="colorize0" title="Humor">Q15</span></th>
        <th><span class="colorize0" title="Trabajo (incluye trabajos del hogar)">Q16</span></th>
        <th><span class="colorize0" title="Relaciones Personales">Q17</span></th>
        <th><span class="colorize0" title="Caminar">Q18</span></th>
        <th><span class="colorize0" title="Disfrutar la Vida">Q19</span></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pros.each do |pro| %>
        <tr>
          <td class = 'colorize<%= pro.q1 %>'><%= pro.q1 %></td>
          <td class = 'colorize<%= pro.q2 %>'><%= pro.q2 %></td>
          <td class = 'colorize<%= pro.q3 %>'><%= pro.q3 %></td>
          <td class = 'colorize<%= pro.q4 %>'><%= pro.q4 %></td>
          <td class = 'colorize<%= pro.q5 %>'><%= pro.q5 %></td>
          <td class = 'colorize<%= pro.q6 %>'><%= pro.q6 %></td>
          <td class = 'colorize<%= pro.q7 %>'><%= pro.q7 %></td>
          <td class = 'colorize<%= pro.q8 %>'><%= pro.q8 %></td>
          <td class = 'colorize<%= pro.q9 %>'><%= pro.q9 %></td>
          <td class = 'colorize<%= pro.q10 %>'><%= pro.q10 %></td>
          <td class = 'colorize<%= pro.q11 %>'><%= pro.q11 %></td>
          <td class = 'colorize<%= pro.q12 %>'><%= pro.q12 %></td>
          <td class = 'colorize<%= pro.q13 %>'><%= pro.q13 %></td>
          <td class = 'colorize<%= pro.q14 %>'><%= pro.q14 %></td>
          <td class = 'colorize<%= pro.q15 %>'><%= pro.q15 %></td>
          <td class = 'colorize<%= pro.q16 %>'><%= pro.q16 %></td>
          <td class = 'colorize<%= pro.q17 %>'><%= pro.q17 %></td>
          <td class = 'colorize<%= pro.q18 %>'><%= pro.q18 %></td>
          <td class = 'colorize<%= pro.q19 %>'><%= pro.q19 %></td>

          <td><%= link_to 'Mostrar', pro %></td>
          <td><%= link_to 'Borrar', pro, method: :delete, data: { confirm: 'Estas seguro que deseas borrar esta encuesta?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Editar', edit_patient_path(@patient) %> |
<%= link_to 'Regresar', patients_path %>