config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :patients
  resources :pros
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

  get '/:page'=> 'static#show'


  root to: 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :patients
  belongs_to :user
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])
    @patients = @doctor.patients
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :address, :phone, :title, :email, :experience)
    end

    def authentication_doctors

    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nombre" %>
    <%= form.text_field :name, id: :doctor_name %>
  </div>

  <div class="field">
    <%= form.label "Dirección" %>
    <%= form.text_field :address, id: :doctor_address %>
  </div>

  <div class="field">
    <%= form.label "Teléfono" %>
    <%= form.text_field :phone, id: :doctor_phone %>
  </div>

  <div class="field">
    <%= form.label "Título" %>
    <%= form.text_field :title, id: :doctor_title %>
  </div>

  <div class="field">
    <%= form.label "Correo electrónico" %>
    <%= form.text_field :email, id: :doctor_email %>
  </div>

  <div class="field">
    <%= form.label "Experiencia" %>
    <%= form.text_area :experience, id: :doctor_experience %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar Perfil" %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Mostrar', @doctor %> |
<%= link_to 'Regresar', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Título</th>
      <th>Correo electrónico</th>
      <th>Experiencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= link_to doctor.name, doctor_path(doctor) %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.phone %></td>
        <td><%= doctor.title %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.experience %></td>
        <td><%= link_to 'Borrar', doctor, method: :delete, data: { confirm: 'Estas seguro que deseas borrar el perfil?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Regresar', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @doctor.phone %>
</p>

<p>
  <strong>Título:</strong>
  <%= @doctor.title %>
</p>

<p>
  <strong>Correo electrónico:</strong>
  <%= @doctor.email %>
</p>

<p>
  <strong>Experiencia:</strong>
  <%= @doctor.experience %>
</p>

<div>
  <h1>Pacientes</h1>
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Dirección</th>
        <th>Fecha de Nacimiento</th>
        <th>Comentarios</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td><%= link_to patient.name, patient %></td>
          <td><%= patient.address %></td>
          <td><%= patient.dob %></td>
          <td><%= patient.comment %></td>
          <td><%= link_to 'Borrar', patient, method: :delete, data: { confirm: 'Estas seguro que deseas borrar a este paciente?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Editar', edit_doctor_path(@doctor) %> |
<%= link_to 'Regresar', doctors_path %>