config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :patients
  resources :pros
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

  get '/:page'=> 'static#show'


  root to: 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pro.rb
class Pro < ApplicationRecord
  validates :patient_id, :q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :q11, :q12, :q13, :q14, :q15, :q16, :q17, :q18, :q19, presence: true
end

app/controllers/pros_controller.rb
class ProsController < ApplicationController
  before_action :set_pro, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /pros
  # GET /pros.json
  def index
    @pros = Pro.all
    @patients = Patient.all
  end

  # GET /pros/1
  # GET /pros/1.json
  def show
    @pro = Pro.find(params[:id])
    @patient = Patient.find(@pro.patient_id)
    @user = User.find_by(id: 11)
  end

  # GET /pros/new
  def new
    @pro = Pro.new
  end

  # GET /pros/1/edit
  def edit
  end

  # POST /pros
  # POST /pros.json
  def create
    @pro = Pro.new(pro_params)

    respond_to do |format|
      if @pro.save
        format.html { redirect_to @pro, notice: 'Pro was successfully created.' }
        format.json { render :show, status: :created, location: @pro }
      else
        format.html { render :new }
        format.json { render json: @pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pros/1
  # PATCH/PUT /pros/1.json
  def update
    respond_to do |format|
      if @pro.update(pro_params)
        format.html { redirect_to @pro, notice: 'Pro was successfully updated.' }
        format.json { render :show, status: :ok, location: @pro }
      else
        format.html { render :edit }
        format.json { render json: @pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pros/1
  # DELETE /pros/1.json
  def destroy
    @pro.destroy
    respond_to do |format|
      format.html { redirect_to pros_url, notice: 'Pro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pro
      @pro = Pro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pro_params
      params.require(:pro).permit(:patient_id, :q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :q11, :q12, :q13, :q14, :q15, :q16, :q17, :q18, :q19, :current, :others, :severity)
    end
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/views/pros/_form.html.erb
<%= form_with(model: pro, local: true) do |form| %>
  <% if pro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pro.errors.count, "error") %> prohibited this pro from being saved:</h2>

      <ul>
      <% pro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span>this will be removed, handled automatically with logins</span>
  <div class="field">
    <%= form.label "Patient's ID" %>
    <%= form.number_field :patient_id, id: :pro_patient_id %>
  </div>

  <div>
    <p>Comúnmente los pacientes oncológicos pueden tener una variedad de síntomas. Estos síntomas pueden o no estar asociados al tratamiento que reciben como la quimioterapia o radioterapia. Por favor lee los siguientes síntomas y si has presentado alguno contesta que tan severo fue.
    </p>
  </div>



  <% levels = { 'No aplica' => 0, 'Leve' => 1, 'Moderado' => 2, 'Severo' => 3, 'Insoportable' => 4 }%>
<table>
  <thead>
    <tr>
      <th>Sintoma</th>
      <th>No Aplica</th>
      <th>Leve</th>
      <th>Moderado</th>
      <th>Severo</th>
      <th>Insoportable</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Dolor</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q1, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Falta de Aliento o  Tos</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q2, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Nausea/Vomito</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q3, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Fatiga o Somnolencia</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q4, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Angustia</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q5, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Diarrea</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q6, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Problemas de Atencion, Memoria o Coordinacion</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q7, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Falta de Apetito</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q8, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Constipación</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q9, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Resequedad u otros malestares en la boca</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q10, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Insomnio</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q11, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>


    <tr>
      <td>Tristeza</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q12, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>

    <tr>
      <td>Fiebre</td>
      <% list = levels
         list.each {|x| %>
          <td><%= radio_button(:pro, :q13, x[1] )%> <span><%=x[0]%></span> </td>
      <% } %>
    </tr>
  </tbody>
</table>

  <div>
    <p>Los síntomas, a mayor o menor medida, a menudo afectan la manera en la que vivimos el día a día y realizamos nuestras labores diarias. Por favor lee las siguientes preguntas y contesta si alguno de los síntomas o la enfermedad en si han afectado su vida de alguna manera.
    </p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Area de Afectacion</th>
        <th>No Aplica</th>
        <th>Leve</th>
        <th>Moderado</th>
        <th>Severo</th>
        <th>Insoportable</th>
      </tr>
    </thead>
    <tbody>

      <tr>
        <td>Actividad General</td>
        <% list = levels
           list.each {|x| %>
            <td><%= radio_button(:pro, :q14, x[1] )%> <span><%=x[0]%></span> </td>
        <% } %>
      </tr>

      <tr>
        <td>Humor</td>
        <% list = levels
           list.each {|x| %>
            <td><%= radio_button(:pro, :q15, x[1] )%> <span><%=x[0]%></span> </td>
        <% } %>
      </tr>

      <tr>
        <td>Trabajo (incluye trabajos del hogar)</td>
        <% list = levels
           list.each {|x| %>
            <td><%= radio_button(:pro, :q16, x[1] )%> <span><%=x[0]%></span> </td>
        <% } %>
      </tr>

      <tr>
        <td>Relaciones Personales</td>
        <% list = levels
           list.each {|x| %>
            <td><%= radio_button(:pro, :q17, x[1] )%> <span><%=x[0]%></span> </td>
        <% } %>
      </tr>

      <tr>
        <td>Caminar</td>
        <% list = levels
           list.each {|x| %>
            <td><%= radio_button(:pro, :q18, x[1] )%> <span><%=x[0]%></span> </td>
        <% } %>
      </tr>

      <tr>
        <td>Disfrutar la vida</td>
        <% list = levels
           list.each {|x| %>
            <td><%= radio_button(:pro, :q19, x[1] )%> <span><%=x[0]%></span> </td>
        <% } %>
      </tr>
    </tbody>
  </table>

  <div class="field">
    <%= form.label "Sus sintomas son actuales? cuando ocurrieron? Explique a continuacion" %>
    <%= form.text_area :current, id: :pro_current %>
  </div>

  <div class="field">
    <%= form.label "Tiene usted otros sintomas? Explique a continuacion" %>
    <%= form.text_area :others, id: :pro_others %>
  </div>

  <div>
    <% levels = { 'No aplica' => 0, 'Leve' => 1, 'Moderado' => 2, 'Severo' => 3, 'Insoportable' => 4 }%>
    <%= form.label "Con que severidad categorizaria sus sintomas de la pregunta anterior?"%>
    <% list = levels
    list.each {|x| %>
      <%= radio_button(:pro, :severity, x[1] )%> <span><%=x[0]%></span>
    <% } %>

  <div class="actions">
    <%= form.submit "Guardar Encuesta" %>
  </div>
<% end %>

app/views/pros/edit.html.erb
<h1>Editing Pro</h1>

<%= render 'form', pro: @pro %>

<%= link_to 'Show', @pro %> |
<%= link_to 'Back', pros_path %>

app/views/pros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pros</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Date</th>
      <th><span class="colorize0" title="Dolor">Q1</span></th>
      <th><span class="colorize0" title="Falta de Aliento o Tos">Q2</span></th>
      <th><span class="colorize0" title="Nausea o Vómito">Q3</span></th>
      <th><span class="colorize0" title="Fatiga o Somnolencia">Q4</span></th>
      <th><span class="colorize0" title="Angustia">Q5</span></th>
      <th><span class="colorize0" title="Diarrea">Q6</span></th>
      <th><span class="colorize0" title="Problemas de Atención, Memoria o Coordinación">Q7</span></th>
      <th><span class="colorize0" title="Falta de Apetito">Q8</span></th>
      <th><span class="colorize0" title="Constipación">Q9</span></th>
      <th><span class="colorize0" title="Resequedad u otros Malestares en la Boca">Q10</span></th>
      <th><span class="colorize0" title="Insomnio">Q11</span></th>
      <th><span class="colorize0" title="Tristeza">Q12</span></th>
      <th><span class="colorize0" title="Fiebre">Q13</span></th>
      <th><span class="colorize0" title="Actividad General">Q14</span></th>
      <th><span class="colorize0" title="Humor">Q15</span></th>
      <th><span class="colorize0" title="Trabajo (incluye trabajos del hogar)">Q16</span></th>
      <th><span class="colorize0" title="Relaciones Personales">Q17</span></th>
      <th><span class="colorize0" title="Caminar">Q18</span></th>
      <th><span class="colorize0" title="Disfrutar la Vida">Q19</span></th>
      <th>Others?</th>
      <th>Severity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pros.each do |pro| %>
      <tr>
        <td><% patient = @patients.find(pro.patient_id)%>
          <%= link_to patient.name, patient_path(patient) %></td>
        <td><%= pro.created_at %></td>
        <td class = 'colorize<%= pro.q1 %>'><%= pro.q1 %></td>
        <td class = 'colorize<%= pro.q2 %>'><%= pro.q2 %></td>
        <td class = 'colorize<%= pro.q3 %>'><%= pro.q3 %></td>
        <td class = 'colorize<%= pro.q4 %>'><%= pro.q4 %></td>
        <td class = 'colorize<%= pro.q5 %>'><%= pro.q5 %></td>
        <td class = 'colorize<%= pro.q6 %>'><%= pro.q6 %></td>
        <td class = 'colorize<%= pro.q7 %>'><%= pro.q7 %></td>
        <td class = 'colorize<%= pro.q8 %>'><%= pro.q8 %></td>
        <td class = 'colorize<%= pro.q9 %>'><%= pro.q9 %></td>
        <td class = 'colorize<%= pro.q10 %>'><%= pro.q10 %></td>
        <td class = 'colorize<%= pro.q11 %>'><%= pro.q11 %></td>
        <td class = 'colorize<%= pro.q12 %>'><%= pro.q12 %></td>
        <td class = 'colorize<%= pro.q13 %>'><%= pro.q13 %></td>
        <td class = 'colorize<%= pro.q14 %>'><%= pro.q14 %></td>
        <td class = 'colorize<%= pro.q15 %>'><%= pro.q15 %></td>
        <td class = 'colorize<%= pro.q16 %>'><%= pro.q16 %></td>
        <td class = 'colorize<%= pro.q17 %>'><%= pro.q17 %></td>
        <td class = 'colorize<%= pro.q18 %>'><%= pro.q18 %></td>
        <td class = 'colorize<%= pro.q19 %>'><%= pro.q19 %></td>
        <td> <%=pro.others%> </td>
        <td class = 'colorize<%= pro.severity%>'><%= pro.severity %></td>

        <td><%= link_to 'Show', pro %></td>
        <td><%= link_to 'Delete', pro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pro', new_pro_path %>

app/views/pros/new.html.erb
<h1>New Pro</h1>

<%= render 'form', pro: @pro %>

<%= link_to 'Back', pros_path %>

app/views/pros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= link_to @patient.name, patient_path(@patient) %>
</p>

<p>
  <strong>Q1:</strong>
  <%= @pro.q1 %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @pro.q2 %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @pro.q3 %>
</p>

<p>
  <strong>Q4:</strong>
  <%= @pro.q4 %>
</p>

<p>
  <strong>Q5:</strong>
  <%= @pro.q5 %>
</p>

<p>
  <strong>Q6:</strong>
  <%= @pro.q6 %>
</p>

<p>
  <strong>Q7:</strong>
  <%= @pro.q7 %>
</p>

<p>
  <strong>Q8:</strong>
  <%= @pro.q8 %>
</p>

<p>
  <strong>Q9:</strong>
  <%= @pro.q9 %>
</p>

<p>
  <strong>Q10:</strong>
  <%= @pro.q10 %>
</p>

<p>
  <strong>Q11:</strong>
  <%= @pro.q11 %>
</p>

<p>
  <strong>Q12:</strong>
  <%= @pro.q12 %>
</p>

<p>
  <strong>Q13:</strong>
  <%= @pro.q13 %>
</p>

<p>
  <strong>Q14:</strong>
  <%= @pro.q14 %>
</p>

<p>
  <strong>Q15:</strong>
  <%= @pro.q15 %>
</p>

<p>
  <strong>Q16:</strong>
  <%= @pro.q16 %>
</p>

<p>
  <strong>Q17:</strong>
  <%= @pro.q17 %>
</p>

<p>
  <strong>Q18:</strong>
  <%= @pro.q18 %>
</p>

<p>
  <strong>Q19:</strong>
  <%= @pro.q19 %>
</p>

<p>
  <strong>Los sintomas son actuales?</strong>
  <%= @pro.current %>
</p>

<p>
  <strong>Tiene otros sintomas?</strong>
  <%= @pro.others %>
</p>

<p>
  <strong>Con que severidad los categoriza?</strong>
  <%= @pro.severity%>
</p>

<%= link_to 'Edit', edit_pro_path(@pro) %> |
<%= link_to 'Back', pros_path %>