config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :patients
  resources :pros
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

  get '/:page'=> 'static#show'


  root to: 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prosite</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row navbar-row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 navbar-container">

          <a href= "<%= '/home' %>"  class="navbar-brand">AVISO</a>

          <nav class="navbar navbar-full">

            <div class="collapse navbar-toggleable-md">

                <ul class="nav navbar-nav">
                    <li class="nav-item">
                      <%= link_to 'Home', '/home', :class => "nav-link"%>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Contáctanos', '/Contactanos', :class=> "nav-link"%>
                    </li>
<!---
                    <li class="nav-item">
                          <%= link_to 'Doctores', doctors_path, :class => "nav-link" %>
                    </li>
                    <li class="nav-item">
                          <%= link_to 'Pacientes', patients_path, :class => "nav-link" %>
                    </li>
                    <li class="nav-item">
                          <%= link_to 'Pros', pros_path, :class => "nav-link" %>
                    </li>
                    <li class="nav-item">
                      <% if logged_in? %>
                         <%= link_to "Salir", logout_path, :class =>"nav-link" %>
                       <% else %>
                         <%= link_to "Entrar", login_path, :class =>"nav-link"%>
                       <% end %>
--->
                    </li>  <li class="nav-item">
                        <%= link_to 'Teoría', '/teoria', :class => "nav-link"%>
                      </li>
                </ul>
            </div>
        </nav>

        <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
            &#9776;
        </button>

      </div>
    </div>

    <div class="tm-page-content">
      <%= yield %>
    </div>

    <p>
      <% if logged_in? %>
         <%= "Identificado como: #{current_user.email}" %>
         <%= link_to "(Cerrar Sesión)", logout_path %>
       <% end %>
     </p>

  </body>
</html>